baseURL = "https://spectare.nl/"
languageCode = "en-us"
theme = "ananke"
title = "Spectare"

DefaultContentLanguage = "en" 
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
SectionPagesMenu = "main" 
enableRobotsTXT = true 
googleAnalytics = "" 

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[params]
description = "The digital world changes the way you work"
facebook = ""
favicon = ""
github = "https://github.com/olger"
gitlab = ""
instagram = ""
linkedin = "https://www.linkedin.com/in/owarnier"
mastodon = ""
rss = ""
site_logo = ""
slack = ""
stackoverflow = ""
twitter = "https://twitter.com/owarnier"
youtube = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
featured_image = "/images/sight.jpg"
recent_posts_number = 6
show_reading_time = true
